import { chromium } from '@playwright/test';
const b=await chromium.connectOverCDP('http://localhost:9222');
const ctx=b.contexts()[0];const page=ctx.pages()[0];
page.setDefaultTimeout(12000);
const net=[],errs=[];
page.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,160));});
page.on('response',r=>{if(r.url().startsWith('http')&&(r.status()>=400||/saha_visits/i.test(r.url())))net.push(`${r.status()} ${r.request().method()} ${r.url().slice(40,90)}`);});
const s=await ctx.newCDPSession(page);
await s.send('Emulation.setGeolocationOverride',{latitude:39.920757,longitude:32.852778,accuracy:18});
await page.evaluate(()=>{history.pushState({},'','/visits/check-in/d0825993-c211-4fb1-b054-db39ce9472ac');dispatchEvent(new PopStateEvent('popstate'));});
await page.waitForTimeout(3500);
await page.getByRole('button',{name:/Check-in Yap/}).click();
await page.waitForTimeout(4000);
const info=await page.evaluate(()=>({url:location.pathname,txt:document.body.innerText.replace(/\s+/g,' ').slice(0,250)}));
console.log('URL',info.url);console.log('TXT',info.txt);
console.log('NET',JSON.stringify([...new Set(net)].slice(0,5)));
if(errs.length)console.log('ERR',JSON.stringify([...new Set(errs)].slice(0,3)));
await b.close();
